#! /bin/bash
CONFIG=$1
source $CONFIG

echo -e "\e[36mMake rescale commands for distance feature\e[39m"
bash scripts/make_rescale_commands.sh $CONFIG

echo -e "\e[32mRun rescale commands for distance feature\e[39m"

if [ $GEN_COMMANDS_ONLY != "T" ];then

  cat records/record_rescale_COMMANDS.sh | parallel -j30 --joblog logs/rescale_status.log  &> logs/rescale_commands.log 

   echo -e "\e[34mLogged at logs/corr_commands.log, logs/corr_jobstatus.log\e[39m"

  # Parallel returns empty stderrs by default, remove them
  find "errors" -maxdepth 1 -name "error_rescale*" -empty -delete
 
  # Parse parallel joblog to find nonzero exit codes
  jobswitherrors=`bash scripts/check_joblog.sh logs/corr_jobstatus.log`

  if [ -n "$jobswitherrors" ];then
    echo -e "\e[91Errors found while inverting scale of following distance measures:\e[39m"
    echo -e "\e[91mSee error logs at:\e[39m"
    echo -e `echo $jobswitherrors | sed 's/ /\r/g'`
    exit 1
  else
    echo -e "\e[35mEuclidean and Bray-Curtis features rescaled (elutions/processed_elutions/*.feat.rescale.ordered)\e[39m"
  fi
fi  


