python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix elutions/processed_elutions/head_all_expconcat_elut_expnormspeccounts*euclidean.feat.ordered --output_filename .rescale.ordered --features euclidean --min 0 --sep , --inverse  > logs/log_rescale_head_all_expconcat_elut_expnormspeccounts*euclidean.feat.ordered 2> logs/error_rescale_head_all_expconcat_elut_expnormspeccounts*euclidean.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix  --output_filename .rescale.ordered --features braycurtis --min 0 --sep , --inverse > logs/log_rescale_head_all_expconcat_elut_expnormspeccounts*braycurtis.feat.ordered 2> logs/error_rescale_head_all_expconcat_elut_expnormspeccounts*braycurtis.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix elutions/processed_elutions/head_wheat_OP_WheatGrassSEC_20170202_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered --output_filename .rescale.ordered --features euclidean --min 0 --sep , --inverse  > logs/log_rescale_head_wheat_OP_WheatGrassSEC_20170202_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered 2> logs/error_rescale_head_wheat_OP_WheatGrassSEC_20170202_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix  --output_filename .rescale.ordered --features braycurtis --min 0 --sep , --inverse > logs/log_rescale_head_wheat_OP_WheatGrassSEC_20170202_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered 2> logs/error_rescale_head_wheat_OP_WheatGrassSEC_20170202_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix elutions/processed_elutions/head_wheat_wgIEF_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered --output_filename .rescale.ordered --features euclidean --min 0 --sep , --inverse  > logs/log_rescale_head_wheat_wgIEF_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered 2> logs/error_rescale_head_wheat_wgIEF_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix  --output_filename .rescale.ordered --features braycurtis --min 0 --sep , --inverse > logs/log_rescale_head_wheat_wgIEF_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered 2> logs/error_rescale_head_wheat_wgIEF_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix elutions/processed_elutions/head_wheat_wgSEC1_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered --output_filename .rescale.ordered --features euclidean --min 0 --sep , --inverse  > logs/log_rescale_head_wheat_wgSEC1_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered 2> logs/error_rescale_head_wheat_wgSEC1_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix  --output_filename .rescale.ordered --features braycurtis --min 0 --sep , --inverse > logs/log_rescale_head_wheat_wgSEC1_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered 2> logs/error_rescale_head_wheat_wgSEC1_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix elutions/processed_elutions/head_wheat_wheatgermIEX_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered --output_filename .rescale.ordered --features euclidean --min 0 --sep , --inverse  > logs/log_rescale_head_wheat_wheatgermIEX_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered 2> logs/error_rescale_head_wheat_wheatgermIEX_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix  --output_filename .rescale.ordered --features braycurtis --min 0 --sep , --inverse > logs/log_rescale_head_wheat_wheatgermIEX_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered 2> logs/error_rescale_head_wheat_wheatgermIEX_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix elutions/processed_elutions/head_wheat_WheatGermSEC_07-2015_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered --output_filename .rescale.ordered --features euclidean --min 0 --sep , --inverse  > logs/log_rescale_head_wheat_WheatGermSEC_07-2015_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered 2> logs/error_rescale_head_wheat_WheatGermSEC_07-2015_virNOG_singleexp_elut_expnormspeccounts*euclidean.feat.ordered
python /project/cmcwhite/github/protein_complex_maps/protein_complex_maps/features/normalize_features.py --input_feature_matrix  --output_filename .rescale.ordered --features braycurtis --min 0 --sep , --inverse > logs/log_rescale_head_wheat_WheatGermSEC_07-2015_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered 2> logs/error_rescale_head_wheat_WheatGermSEC_07-2015_virNOG_singleexp_elut_expnormspeccounts*braycurtis.feat.ordered
