#! /bin/bash
CONFIG=$1
source $CONFIG   
echo -e "\e[36mMake alphabetization commands (records/record_alphabetize_commands_gen.sh"
bash records/record_alphabetize_commands_gen.sh $PCM_DIR

echo -e "\e[32mRun alphabetization commands (records/record_alphabetize_COMMANDS.sh"
cat records/record_alphabetize_COMMANDS.sh | parallel -j30 &> logs/alphabetize_commands.log 
echo -e "\e[34mLogged at logs/alphabetize_commands.log\e[39m"

if [ -f "$(find "elutions/processed_elutions" -name "*.feat.ordered" | head -1)" ] 
then    
    echo -e "\e[35mFeature IDs alphabetized (elutions/processed_elutions/*.feat.ordered\e[39m)"
else
    echo -e "\e[91mNo output files from alphabetizing feature IDs were found (elutions/processed_elutions/*.feat.ordered)\e[39m"
    echo -e "\e[91mExiting\e[39m"
    exit 1
fi
