#! /bin/bash
CONFIG=$1
source $CONFIG

echo -e "\e[32mfeature matrix procession\e[39m"
bash records/record_feature_matrix_processing.sh  

echo -e "\e[32mfeature selection\e[39m"
bash records/record_feature_selection.sh  


echo -e "\e[36mtraining\e[39m"
bash records/record_training.sh 
