#! /bin/bash
CONFIG=$1
source $CONFIG

echo -e "\e[36m Scoring feature matrix with trained model\e[39m"

rm -f errors/error_score
rm -f logs/log_score

echo "python /project/cmcwhite/github/run_TPOT/tpot_predict.py --datafile feature_matrix/${EXP_PREFIX}.featmat --serialized_model training/tpot_${EXP_PREFIX}_fitted_model.p --outfile training/tpot_${EXP_PREFIX}_scored.txt --id_cols 0"  > records/record_score.sh

if [ $GEN_COMMANDS_ONLY != "T" ];then

  bash records/record_score.sh > logs/log_score 2> errors/error_score

  # Check for exit code of command
  status=$?

  if [ ! $status -eq 0 ]; then
    echo -e "\e[91mErrors found while using model to score interactions\e[39m"
    echo -e "\e[91mSee stout at errors/error_score\e[39m"
    echo -e "\e[91mSee errors at errors/error_score\e[39m"

    exit 1
  else
    echo -e "\e[35mInteractions scored (training/tpot_${EXP_PREFIX}_scored.txt)\e[39m"
  fi
fi 
