#! /bin/bash
CONFIG=$1

echo -e "\e[32mFormat input elutions (records/record_format_elutions.sh)\e39m"
bash records/record_format_elutions.sh &> logs/format_elutions.log

# TODO: Add script to perform formatting check

echo -e "\e[34mLogged at logs/format_elutions.log\e[39m"
if [ -f "$(find "elutions/processed_elutions" -name "*.wide" | head -1)" ] 
then    

    echo -e "\e[35mElutions formatted (elutions/processed_elutions/*.wide)\e[39m"
else
    echo -e "\e[91mNo output files from formatting elutions were found (elutions/processed_elutions/*.wide)\e[39m"
    echo -e "\e[91mExiting\e[39m"
exit 1
fi
