#! /bin/bash
CONFIG=$1
source $CONFIG

echo -e "\e[32mGet feature names, saving as $FEAT_FILE\e[39m"

ls elutions/processed_elutions/*pearsonR*ordered > $FEAT_FILE
ls elutions/processed_elutions/*spearmanR*ordered >> $FEAT_FILE
ls elutions/processed_elutions/*braycurtis*rescale.ordered >> $FEAT_FILE
ls elutions/processed_elutions/*euclidean*rescale.ordered >> $FEAT_FILE
