#! /bin/bash
CONFIG=$1
source $CONFIG  
 
echo -e "\e[36mMake alphabetization commands (records/record_alphabetize_commands_gen.sh"

bash records/record_alphabetize_commands_gen.sh $CONFIG

echo -e "\e[32mRun alphabetization commands (records/record_alphabetize_COMMANDS.sh"

cat records/record_alphabetize_COMMANDS.sh | parallel -j30 --joblog logs/alphabetize_jobstatus.log &> logs/alphabetize_commands.log 

echo -e "\e[34mLogged at logs/alphabetize_commands.log\e[39m"

# Remove empty error files (meaning no error)
# Parallel returns an empty stderr by default
find "logs" -maxdepth 1 -name "error_alpha*" -empty -delete


#Look for any errors and report. Error log is cleared out at each run so any new errors are from current run
while read exp
  do
    if [ -f "$(find "logs" -maxdepth 1 -name "error_alpha*" | head -1)" ]
      then
        echo "Errors found while ordering identifiers of features"
        ls logs/error_alpha*
        exit 1
    fi
  done < $EXPLIST


if [ -f "$(find "elutions/processed_elutions" -maxdepth 1 -name "*.feat.ordered" | head -1)" ] 
then    
    echo -e "\e[35mFeature IDs alphabetized (elutions/processed_elutions/*.feat.ordered\e[39m)"
fi

#else
#    echo -e "\e[91mNo output files from alphabetizing feature IDs were found (elutions/processed_elutions/*.feat.ordered)\e[39m"
#    echo -e "\e[91mExiting\e[39m"
#    exit 1
#fi
