#! /bin/bash
CONFIG=$1
source $CONFIG  
 
echo -e "\e[36mMake alphabetization commands (records/record_alphabetize_commands_gen.sh"

bash scripts/make_alphabetize_commands.sh $CONFIG

echo -e "\e[32mRun alphabetization commands (records/record_alphabetize_COMMANDS.sh"

if [ $GEN_COMMANDS_ONLY != "T" ];then

  cat records/record_alphabetize_COMMANDS.sh | parallel -j30 --joblog logs/alphabetize_jobstatus.log &> logs/alphabetize_commands.log 
  
  echo -e "\e[34mLogged at logs/alphabetize_commands.log, logs/alphabetize_jobstatus.log\e[39m"

  # Parallel returns empty stderrs by default, remove them
  find "errors" -maxdepth 1 -name "error_alpha*" -empty -delete
 
  # Parse parallel joblog to find nonzero exit codes
  jobswitherrors=`bash scripts/check_joblog.sh logs/alphabetize_jobstatus.log`
 
  if [ -n "$jobswitherrors" ];then 
    echo -e "\e[91mErrors found while ordering identifiers of features\e[39m" 
    echo -e "\e[91mSee error logs at:\e[39m"
    echo -e `echo $jobswitherrors | sed 's/ /\r/g'`
    exit 1
  else
    echo -e "\e[35mFeature IDs alphabetized (elutions/processed_elutions/*.feat.ordered\e[39m)"
  fi
 
fi
