#! /bin/bash
CONFIG=$1
source $CONFIG

echo "EXPLIST=$EXPLIST"
echo "PCM_DIR=$PCM_DIR"
echo "ADD_POISSON_NOISE=$ADD_POISSON_NOISE"
echo "POISSON_REPS=$POISSON_REPS"     


# Check if input files exist
if [ -f "$(find "elutions/processed_elutions" -name "*.wide" | head -1)" ]
    then

        echo -e "\e[35mElutions formatted (elutions/processed_elutions/*.wide)\e[39m"
    else
        echo -e "\e[91mNo output files from formatting elutions were found (elutions/processed_elutions/*.wide)\e[39m"
        echo -e "\e[91mExiting\e[39m"
    exit 1
fi

if [[ -z $PCM_DIR ]]; then
  echo 'PCM_DIR undefined in config file, should point to protein_complex_maps repository ex. PCM_DIR=/home/github/protein_complex_maps'
  exit
fi

if [[ $ADD_POISSON_NOISE != [TF] ]]; then
  echo "ADD_POISSON_NOISE must be set to T or F in config file"

  echo 'Set ADD_POISSON_NOISE=T for count based input data, otherwise ADD_POISSON_NOISE=F for e.g. intensity data.'
  exit 1
fi
###################

###################
#Code


echo -e "\e[36mCreate correlation commands (records/record_corr_commands_gen.sh)\ndefault 5 replications with poisson noise, use up to 100 for final calculation.\nSet ADD_POISSON_NOISE=F for non-count data such as intensities\e[39m"

bash scripts/make_corr_commands.sh $CONFIG

echo -e "\e[32mRun correlation commands (records/record_corr_COMMANDs.sh)"

if [ $GEN_COMMANDS_ONLY != "T" ];then
  
  cat records/record_corr_COMMANDS.sh | parallel -j30 --joblog logs/corr_jobstatus.log &> logs/corr_commands.log
  
  echo -e "\e[34mLogged at logs/corr_commands.log, logs/corr_jobstatus.log\e[39m"

  # Parallel returns empty stderrs by default, remove them
  find "errors" -maxdepth 1 -name "error_corr*" -empty -delete
 
  # Parse parallel joblog to find nonzero exit codes
  jobswitherrors=`bash scripts/check_joblog.sh logs/corr_jobstatus.log`

  if [ -n "$jobswitherrors" ];then
    echo -e "\e[91Errors found during calculation of following features:\e[39m"
    echo -e "\e[91mSee error logs at:\e[39m"
    echo -e `echo $jobswitherrors | sed 's/ /\r/g'`
    exit 1
  else
    echo -e "\e[35mFeatures calculated (elutions/processed_elutions/*.feat)\e[39m"
  fi
fi 
