#! /bin/bash
CONFIG=$1
source $CONFIG

echo -e "\e[32mfeature matrix procession"
bash records/record_feature_matrix_processing.sh  

echo -e "\e[32mfeature selection"
bash records/record_feature_selection.sh  


echo -e "\e[36mtraining"
bash records/record_training.sh 
